import type { NodeTemplate } from "../types/workflow";

export const NODE_TEMPLATES: NodeTemplate[] = [
  // ── Entry / Exit ──────────────────────────────────────────
  {
    type: "start",
    category: "start",
    label: "Start",
    description: "工作流开始节点，无输入，输出用户自定义",
    icon: "▶",
    color: "#10B981",
  },
  {
    type: "end",
    category: "end",
    label: "End",
    description: "工作流结束节点，输入用户自定义，无输出",
    icon: "⏹",
    color: "#EF4444",
  },
  // ── I/O ───────────────────────────────────────────────────
  {
    type: "input",
    category: "io",
    label: "Input",
    description: "等待外部数据注入，暂停工作流直到收到输入",
    icon: "⌨",
    color: "#F59E0B",
  },
  // ── Core actions ──────────────────────────────────────────
  {
    type: "action",
    category: "core",
    label: "Action",
    description: "通用动作节点，config.action_type 指定具体动作",
    icon: "⚡",
    color: "#6366F1",
  },
  {
    type: "pass",
    category: "core",
    label: "Pass",
    description: "数据透传/转换节点",
    icon: "→",
    color: "#6B7280",
  },
  {
    type: "core.log",
    category: "core",
    label: "Log",
    description: "将输入数据输出到终端日志，输出空消息",
    icon: "📝",
    color: "#64748B",
  },
  // ── Control flow ──────────────────────────────────────────
  {
    type: "if",
    category: "control",
    label: "If",
    description: "条件分支：根据输入值路由到 true/false 端口",
    icon: "🔀",
    color: "#3B82F6",
  },
  {
    type: "switch",
    category: "control",
    label: "Switch",
    description: "多路分支：按 case 值路由",
    icon: "⑂",
    color: "#3B82F6",
  },
  {
    type: "for",
    category: "control",
    label: "For",
    description: "遍历数组，输入 items(array)，输出 results(array)",
    icon: "🔁",
    color: "#8B5CF6",
  },
  {
    type: "while",
    category: "control",
    label: "While",
    description: "条件循环，输入 initial + condition，输出 result",
    icon: "↺",
    color: "#8B5CF6",
  },
  {
    type: "retry",
    category: "control",
    label: "Retry",
    description: "失败重试节点，自动按配置重试",
    icon: "🔄",
    color: "#F59E0B",
  },
  // ── Data ops ──────────────────────────────────────────────
  {
    type: "merge",
    category: "data",
    label: "Merge",
    description: "合并多个输入到单一输出",
    icon: "⇒",
    color: "#14B8A6",
  },
  {
    type: "split",
    category: "data",
    label: "Split",
    description: "拆分单一输入到多个输出",
    icon: "⇒",
    color: "#14B8A6",
  },
  // ── Composite ─────────────────────────────────────────────
  {
    type: "group",
    category: "composite",
    label: "Group",
    description: "封装内部子图，外部可见端口由 mappings 定义",
    icon: "📦",
    color: "#EC4899",
  },
  {
    type: "subflow",
    category: "composite",
    label: "Subflow",
    description: "引用并执行外部工作流",
    icon: "📁",
    color: "#EC4899",
  },
];
