import type { NodeTemplate } from "../types/workflow";

export const NODE_TEMPLATES: NodeTemplate[] = [
  {
    type: "start",
    category: "start",
    label: "Start",
    description: "工作流开始节点",
    icon: "▶",
    color: "#10B981",
  },
  {
    type: "end",
    category: "end",
    label: "End",
    description: "工作流结束节点",
    icon: "⏹",
    color: "#EF4444",
  },
  {
    type: "action",
    category: "basic",
    label: "Action",
    description: "执行具体动作",
    icon: "⚡",
    color: "#6B7280",
  },
  {
    type: "pass",
    category: "basic",
    label: "Pass",
    description: "数据透传节点",
    icon: "🔄",
    color: "#6B7280",
  },
  {
    type: "if",
    category: "control",
    label: "If",
    description: "条件分支节点",
    icon: "🔀",
    color: "#3B82F6",
  },
  {
    type: "switch",
    category: "control",
    label: "Switch",
    description: "多路分支节点",
    icon: "🔄",
    color: "#3B82F6",
  },
  {
    type: "for",
    category: "control",
    label: "For",
    description: "For 循环节点",
    icon: "🔁",
    color: "#3B82F6",
  },
  {
    type: "while",
    category: "control",
    label: "While",
    description: "While 循环节点",
    icon: "🔁",
    color: "#8B5CF6",
  },
  {
    type: "retry",
    category: "control",
    label: "Retry",
    description: "重试节点",
    icon: "🔄",
    color: "#F59E0B",
  },
  {
    type: "merge",
    category: "data",
    label: "Merge",
    description: "合并数据节点",
    icon: "📥",
    color: "#14B8A6",
  },
  {
    type: "split",
    category: "data",
    label: "Split",
    description: "拆分数据节点",
    icon: "📤",
    color: "#14B8A6",
  },
  {
    type: "group",
    category: "composite",
    label: "Group",
    description: "分组节点",
    icon: "📦",
    color: "#14B8A6",
  },
  {
    type: "subflow",
    category: "composite",
    label: "Subflow",
    description: "子工作流节点",
    icon: "📁",
    color: "#EC4899",
  },
  {
    type: "core.log",
    category: "core",
    label: "Log",
    description: "输出日志信息",
    icon: "📝",
    color: "#6B7280",
  },
  {
    type: "core.set_var",
    category: "core",
    label: "Set Variable",
    description: "设置变量值",
    icon: "📦",
    color: "#6B7280",
  },
  {
    type: "core.wait",
    category: "core",
    label: "Wait",
    description: "等待指定时间",
    icon: "⏳",
    color: "#6B7280",
  },
  {
    type: "core.if",
    category: "core",
    label: "If Condition",
    description: "条件判断",
    icon: "🔀",
    color: "#6B7280",
  },
  {
    type: "core.switch",
    category: "core",
    label: "Switch",
    description: "多条件分支",
    icon: "🔄",
    color: "#6B7280",
  },
  {
    type: "core.loop",
    category: "core",
    label: "Loop",
    description: "循环执行",
    icon: "🔁",
    color: "#6B7280",
  },
  {
    type: "browser.navigate",
    category: "browser",
    label: "Navigate",
    description: "导航到指定URL",
    icon: "🌐",
    color: "#8B5CF6",
  },
  {
    type: "browser.click",
    category: "browser",
    label: "Click",
    description: "点击元素",
    icon: "👆",
    color: "#8B5CF6",
  },
  {
    type: "browser.type",
    category: "browser",
    label: "Type",
    description: "输入文本",
    icon: "⌨️",
    color: "#8B5CF6",
  },
  {
    type: "browser.screenshot",
    category: "browser",
    label: "Screenshot",
    description: "截屏",
    icon: "📸",
    color: "#8B5CF6",
  },
  {
    type: "browser.get_text",
    category: "browser",
    label: "Get Text",
    description: "获取文本内容",
    icon: "📄",
    color: "#8B5CF6",
  },
  {
    type: "browser.get_attribute",
    category: "browser",
    label: "Get Attribute",
    description: "获取元素属性",
    icon: "🔍",
    color: "#8B5CF6",
  },
  {
    type: "browser.scroll",
    category: "browser",
    label: "Scroll",
    description: "滚动页面",
    icon: "📜",
    color: "#8B5CF6",
  },
  {
    type: "browser.wait_for",
    category: "browser",
    label: "Wait For",
    description: "等待元素出现",
    icon: "⏸️",
    color: "#8B5CF6",
  },
  {
    type: "tool.http_request",
    category: "tool",
    label: "HTTP Request",
    description: "发送HTTP请求",
    icon: "📡",
    color: "#F59E0B",
  },
  {
    type: "tool.read_file",
    category: "tool",
    label: "Read File",
    description: "读取文件",
    icon: "📖",
    color: "#F59E0B",
  },
  {
    type: "tool.write_file",
    category: "tool",
    label: "Write File",
    description: "写入文件",
    icon: "✍️",
    color: "#F59E0B",
  },
  {
    type: "tool.exec",
    category: "tool",
    label: "Execute Command",
    description: "执行系统命令",
    icon: "💻",
    color: "#F59E0B",
  },
  {
    type: "tool.sleep",
    category: "tool",
    label: "Sleep",
    description: "暂停执行",
    icon: "😴",
    color: "#F59E0B",
  },
  {
    type: "llm",
    category: "other",
    label: "LLM",
    description: "大语言模型节点",
    icon: "🤖",
    color: "#EC4899",
  },
  {
    type: "python",
    category: "other",
    label: "Python",
    description: "Python代码执行",
    icon: "🐍",
    color: "#14B8A6",
  },
  {
    type: "api",
    category: "other",
    label: "API",
    description: "API调用节点",
    icon: "🔌",
    color: "#3B82F6",
  },
  {
    type: "condition",
    category: "other",
    label: "Condition",
    description: "条件节点",
    icon: "❓",
    color: "#8B5CF6",
  },
  {
    type: "loop",
    category: "other",
    label: "Loop",
    description: "循环节点",
    icon: "🔄",
    color: "#F59E0B",
  },
  {
    type: "output",
    category: "other",
    label: "Output",
    description: "输出节点",
    icon: "📤",
    color: "#10B981",
  },
];
